name: 'ng2_hackernews'
version: 0.0.1
description: >
  A HackerNews application made with Angular2 Dart.
author: Andres Araujo <a.araujo.azua@gmail>
homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  firebase: ">=0.5.0 <0.6.0"
  angular2: ">=2.0.0-alpha.27 <3.0.0"
  timeago: any
  less_dart: any
  browser: any
  html: any
transformers:
  - less_dart
#  - angular2
