name: 'ng2_hackernews'
version: 0.0.1
description: >
  A HackerNews application made with Angular2 Dart.
author: Andres Araujo <a.araujo.azua@gmail>
homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  firebase: ">=0.6.0 <0.7.0"
  angular2: "2.0.0-beta.0"
  timeago: any
  less_dart: any
  browser: any
  html: any
  dart_to_js_script_rewriter: '^0.1.0'
transformers:
  - less_dart:
      include_path: ../lib/components/
  - angular2:
      entry_points: web/main.dart
  - dart_to_js_script_rewriter
